mage: node:12.18.2

pipelines:
  branches: 
    development:
      - step:
          name: Deploy to Web
          image: alpine
          deployment: production
          script:
            - apt-get update && apt-get install -y rsync #singkronisasi file
            - apk update && apk add openssh rsync
            - cd $BITBUCKET_CLONE_DIR #direktori project
            - rsync -r -v -e ssh . deploy@147.139.168.144:/var/www/gcore-siscab-web --delete-before --exclude '.git' #path project custom & .git otomatis  terhapus
            - ssh deploy@147.139.168.144 'cd /var/www && cp .env.gcore-siscab-web /var/www/gcore-siscab-web/.env' #copy .env
            - ssh deploy@147.139.168.144 'cd /var/www/gcore-siscab-web && npm install' #instalasi project
            - ssh deploy@147.139.168.144 'cd /var/www/gcore-siscab-web && npm run build' #build project
